### ISSUE TITLE
Recurring crash of Client on JVM

### ISSUE THREAD

**Issue by alkurop** [davidepianca98/KMQTT#19]
Example client runs on JVM, after around 1 minute the app crashes.
I'm using mosquitto broker. It emits 30 to 60 events per second.

 ```
Exception in thread "main" socket.SocketClosedException
	at socket.tcp.Socket.readToBuffer(Socket.kt:47)
	at socket.tcp.Socket.read--5HJl4c(Socket.kt:57)
	at ClientSocket.read--5HJl4c(ClientSocket.kt:32)
	at MQTTClient.check(MQTTClient.kt:312)
	at MQTTClient.step(MQTTClient.kt:376)
	at MQTTClient.run(MQTTClient.kt:385)
	at MainKt.main(Main.kt:16)
	at MainKt.main(Main.kt)


```

**Comment by alkurop** [comment]
Figured out that client disconnected with timeout by the host. No problem in library, closing issues

**Comment by RoustamManookian** [comment]
I am receiving the same Exception.
I am not sure that this is the best approach but this is how I made it.

![socket](https://github.com/davidepianca98/KMQTT/assets/75514218/9af24721-986a-4281-b8b6-78d79cb87136)
![mqttLog](https://github.com/davidepianca98/KMQTT/assets/75514218/b729dd44-25fc-47e2-88c8-e5cf41fc058f)

**Comment by RoustamManookian** [comment]
It is the responsibility of the Client to ensure that the interval between Control Packets being sent does not exceed the Keep Alive value. In the absence of sending any other Control Packets, the Client MUST send a PINGREQ Packet [MQTT-3.1.2-23]

**Comment by davidepianca98** [comment]
Hello, I tested your exact code setting the dispatcher to Dispatchers.IO (I assume you are on the JVM) and connected to test.mosquitto.org and it's working correctly without disconnections even if no messages are going through. The PINGREQ is sent by the client when there is no activity on the connection. 
How often are you receiving messages?
Does adding a periodic publish make the connection stable?
Can you try connecting to test.mosquitto.org to see if you get the SocketClosedException?

**Comment by RoustamManookian** [comment]
How often are you receiving messages?
I am receiving a lot of messages because there are many devices connected and each one sends two messages a minute,  but sending only a few when needed.

Does adding a periodic publish make the connection stable?
I am not publishing periodically, I just make new clients and reSubscribe, and Yes this way, not the connection but the communication is stable. But I'm not sure that this is the best practice.

**Comment by davidepianca98** [comment]
Can you try publishing once a minute and see if the disconnection still happen?
Making a new client is a good way of reconnecting, but the disconnection shouldn't happen in the first place. What broker are you using and with which configuration? Maybe I can try myself.
