### ISSUE TITLE
java.nio.BufferOverflowException when calling 

### ISSUE THREAD

**Issue by growse** [davidepianca98/KMQTT#34]
This only happens on my CI instance, which is a bit less powerful than my desktop. I wonder if there's a race?
```
01-11 17:17:51.247  2605  2633 E TestRunner: java.nio.BufferOverflowException
01-11 17:17:51.247  2605  2633 E TestRunner:    at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:164)
01-11 17:17:51.247  2605  2633 E TestRunner:    at java.nio.ByteBuffer.put(ByteBuffer.java:732)
01-11 17:17:51.247  2605  2633 E TestRunner:    at socket.tcp.Socket.send-GBYM_sE(Socket.kt:19)
01-11 17:17:51.247  2605  2633 E TestRunner:    at mqtt.broker.ClientConnection.writePacket$kmqtt_broker(ClientConnection.kt:103)
01-11 17:17:51.247  2605  2633 E TestRunner:    at mqtt.broker.Session.publish$kmqtt_broker(Session.kt:120)
01-11 17:17:51.247  2605  2633 E TestRunner:    at mqtt.broker.Session.publish-dKY7gkk(Session.kt:168)
01-11 17:17:51.247  2605  2633 E TestRunner:    at mqtt.broker.Broker.publishNormal-Doz7y5Q(Broker.kt:111)
01-11 17:17:51.247  2605  2633 E TestRunner:    at mqtt.broker.Broker.publish-WrwqGuM$kmqtt_broker(Broker.kt:180)
01-11 17:17:51.247  2605  2633 E TestRunner:    at mqtt.broker.Broker.publish-WrwqGuM$kmqtt_broker$default(Broker.kt:121)
01-11 17:17:51.247  2605  2633 E TestRunner:    at mqtt.broker.Broker.publish-dKY7gkk(Broker.kt:224)
01-11 17:17:51.247  2605  2633 E TestRunner:    at mqtt.broker.Broker.publish-XKAnP-8(Broker.kt:244)
01-11 17:17:51.247  2605  2633 E TestRunner:    at org.owntracks.android.testutils.TestWithAnMQTTBrokerImpl.sendFromBroker(TestWithAnMQTTBrokerImpl.kt:46)
```

I'm calling publish on multiple messages, a bit like this:

```
    @RunWith(AndroidJUnit4::class)
    class MyTest {
        @Test
        fun myTest() {
            listOf(
                MessageLocation(),
                MessageCard()
            }.sendFromBroker(broker)
        }

        fun <E : MessageBase> Collection<E>.sendFromBroker(
            broker: Broker,
            topicName: String = "owntracks/someuser/somedevice",
            retain: Boolean = false
        ) = forEach { it.sendFromBroker(broker, topicName, retain) }

        fun MessageBase.sendFromBroker(
            broker: Broker,
            topicName: String = "testTopic",
            retain: Boolean
        ) {            
            this.toJsonBytes()
                .run {
                    broker.publish(
                        true,
                        actualTopic,
                        Qos.AT_LEAST_ONCE,
                        MQTT5Properties(),
                        toUByteArray()
                    )
                }
        }
    }
```

This same code works fine with either:
- KMQTT 0.3.3, fails on 0.4.x.
- Setting the QoS to AT_MOST_ONCE

**Comment by davidepianca98** [comment]
Hello, is it possible to know the size of the payload of the messages you are trying to send?

**Comment by growse** [comment]
First message is 142 bytes, second is 2804 bytes.

**Comment by davidepianca98** [comment]
Should be fixed in https://github.com/davidepianca98/KMQTT/commit/d1e1f4387919ebef35c443c196d046addde3ca99. I will publish a new build soon

**Comment by davidepianca98** [comment]
I assume the problem has been fixed. Please reopen if necessary

**Comment by growse** [comment]
It has, apologies, I did mean to return to this after a bit more testing, but looks good for now. Thanks!
