### ISSUE TITLE
KMQTT Broker - Provide a method to add SecretKeyFactory algorithm  to decrypt the PKCS12 file if device doesn't have it by default.

### ISSUE THREAD

**Issue by nishankhadka09** [davidepianca98/KMQTT#55]
**Ran the KMQTT Broker on Android10 with TLS enabled.**
Ran into the following exception:

> java.io.IOException: exception decrypting data - java.security.NoSuchAlgorithmException: 1.2.840.113549.1.5.12 SecretKeyFactory not available
> at com.android.org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.cryptData(PKCS12KeyStoreSpi.java:730)
> at com.android.org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(PKCS12KeyStoreSpi.java:978)
> at java.security.KeyStore.load(KeyStore.java:1484)
> at socket.tls.TLSServerSocket.<init>(TLSServerSocket.kt:32)
> at socket.ServerSocketLoop.<init>(ServerSocketLoop.kt:15)
> at mqtt.broker.Broker.<init>(Broker.kt:50)
> at mqtt.broker.Broker.<init>(Unknown Source:0)
> at mqtt.broker.Broker.<init>(Broker.kt:20)

**Comment by nishankhadka09** [comment]
Just found out that pBKDF2 is  obsolete.

**Comment by nishankhadka09** [comment]
Tried the follwoing, but ran into exception:"

In `build.gradle.kts` 
```
kotlin {
    explicitApi()

    jvm {
        compilations.all {
           compileTaskProvider.configure {
               compilerOptions {
                   jvmTarget.set(JvmTarget.JVM_21)
               }
           }
        }
    }
...  
sourceSets {
...
val jvmMain by getting {
            dependencies {
                implementation("dnsjava:dnsjava:3.5.2")
                implementation("org.bouncycastle:bcprov-jdk18on:1.78.1")

            }
        }
...
}
...
}
task("shadowJar", ShadowJar::class) {
    duplicatesStrategy =  DuplicatesStrategy.EXCLUDE
    from(kotlin.targets["jvm"].compilations["main"].output)
    mergeServiceFiles()
    manifest {
        attributes(Pair("Main-Class", "MainKt"))
    }
    configurations = kotlin.targets["jvm"].compilations["main"].runtimeDependencyFiles?.let { listOf(it) } ?: emptyList()

}
...
```

Then in the `TLSServerSocket.kt`:

```
...
 init {
        try {
            Security.addProvider(BouncyCastleProvider())
            val keyStore = KeyStore.getInstance("PKCS12", BouncyCastleProvider.PROVIDER_NAME)
            File(broker.tlsSettings!!.keyStoreFilePath).inputStream().use {
                keyStore.load(it, broker.tlsSettings.keyStorePassword?.toCharArray())
            }
            val keyManagerFactory =
                KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm())
            keyManagerFactory.init(keyStore, broker.tlsSettings.keyStorePassword?.toCharArray())

            sslContext.init(keyManagerFactory.keyManagers, null, null)

            val initSession = sslContext.createSSLEngine().session
            initSession.invalidate()
        } catch (e: Exception) {
            close()
           throw e
        }
    }
...
```
Build the broker, and generate JAR file, and added it as library to an android project, but got the following error:

> java.lang.NoClassDefFoundError: Failed resolution of: Lorg/bouncycastle/jce/provider/BouncyCastleProvider;
> at socket.tls.TLSServerSocket.<init>(TLSServerSocket.kt:33)
> at socket.ServerSocketLoop.<init>(ServerSocketLoop.kt:15)
> at mqtt.broker.Broker.<init>(Broker.kt:50)
> at mqtt.broker.Broker.<init>(Unknown Source:0)
> at mqtt.broker.Broker.<init>(Broker.kt:20)
> at com.cistech.oimq.broker.MqttBrokerManager.startBroker(MqttBrokerManager.kt:224)
> at com.cistech.oimq.broker.MqttBrokerManager$prepareBroker$1.invokeSuspend(MqttBrokerManager.kt:211)
> at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:266)
> at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
> at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
> at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
> at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
> at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:816)
> at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
> at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
> Caused by: java.lang.ClassNotFoundException: Didn't find class "org.bouncycastle.jce.provider.BouncyCastleProvider" on path: DexPathList[[zip file "/data/app/com.app.broker-ZW76l_5H4I2xD7hkbQzY-w==/base.apk"],nativeLibraryDirectories=[/data/app/com.app.broker-ZW76l_5H4I2xD7hkbQzY-w==/lib/arm64, /data/app/com.app.broker-ZW76l_5H4I2xD7hkbQzY-w==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]


The project already creates a shadow jar, so I am out of ideas on why does it not add the BouncyCastle dependency that's specified in the gradle.

**Comment by davidepianca98** [comment]
Hey, thank you for posting the issue, I will look into this in the next weeks
