### ISSUE TITLE
Is it compatible with Android?

### ISSUE THREAD

**Issue by Robson96** [davidepianca98/KMQTT#70]
When I try to run it, I get this error:

E  FATAL EXCEPTION: DefaultDispatcher-worker-1 
Process: com.system.process, PID: 11679

**Comment by davidepianca98** [comment]
Hello, please post the full exception. The library is compatible with Android.

**Comment by Robson96** [comment]
I just display this error message 

FATAL EXCEPTION: DefaultDispatcher-worker-3
Process: com.system.process, PID: 10842

**Comment by davidepianca98** [comment]
This is not the actual exception that is triggering the crash. There has to be more a longer stack trace. Otherwise I cannot do much with that info only, unfortunately.

**Comment by RankoR** [comment]
@davidepianca98 I'm getting the same on Android 13 on Pixel 6.

The only log in logcat is

```
FATAL EXCEPTION: DefaultDispatcher-worker-8
                                                                                                    Process: %package%, PID: 22760
```

If I set an exception handler while calling `runSuspend`, it's getting called with this:

```
Exception occured in MQTT: Read to buffer error End Of Stream (-1)
                                                                                                    io.github.davidepianca98.socket.SocketClosedException: Read to buffer error End Of Stream (-1)
                                                                                                    	at io.github.davidepianca98.socket.tcp.Socket.readToBuffer(Socket.kt:65)
                                                                                                    	at io.github.davidepianca98.socket.tcp.Socket.read--5HJl4c(Socket.kt:75)
                                                                                                    	at io.github.davidepianca98.ClientSocket.read--5HJl4c(ClientSocket.kt:40)
                                                                                                    	at io.github.davidepianca98.MQTTClient.check(MQTTClient.kt:389)
                                                                                                    	at io.github.davidepianca98.MQTTClient.step(MQTTClient.kt:466)
                                                                                                    	at io.github.davidepianca98.MQTTClient.run(MQTTClient.kt:476)
                                                                                                    	at io.github.davidepianca98.MQTTClient$runSuspend$2.invokeSuspend(MQTTClient.kt:491)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:829)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
```

This error happens when the device goes to sleep and network activity gets suspended, but it doesn't lead to the crash directly. 

It detects that it's disconnected, then I'm trying to reconnect by creating a new instance and a second later it crashes with the crash log that OP mentioned.

Here are the full logs:

```
2025-01-25 16:25:04.666 22760-22814 PlatformMqttClient      redacted             D  onDisconnected
2025-01-25 16:25:04.668 22760-22814 PlatformMqttClient      redacted             D  Disconnection was not initiated by us, will reconnect after 1000 ms
2025-01-25 16:25:04.678 22760-22814 PlatformMqttClient      redacted             E  Exception occured in MQTT: Read to buffer error End Of Stream (-1)
                                                                                                    io.github.davidepianca98.socket.SocketClosedException: Read to buffer error End Of Stream (-1)
                                                                                                    	at io.github.davidepianca98.socket.tcp.Socket.readToBuffer(Socket.kt:65)
                                                                                                    	at io.github.davidepianca98.socket.tcp.Socket.read--5HJl4c(Socket.kt:75)
                                                                                                    	at io.github.davidepianca98.ClientSocket.read--5HJl4c(ClientSocket.kt:40)
                                                                                                    	at io.github.davidepianca98.MQTTClient.check(MQTTClient.kt:389)
                                                                                                    	at io.github.davidepianca98.MQTTClient.step(MQTTClient.kt:466)
                                                                                                    	at io.github.davidepianca98.MQTTClient.run(MQTTClient.kt:476)
                                                                                                    	at io.github.davidepianca98.MQTTClient$runSuspend$2.invokeSuspend(MQTTClient.kt:491)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:829)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
2025-01-25 16:25:05.670 22760-22814 PlatformMqttClient      redacted             D  connectInternal
2025-01-25 16:25:05.672 22760-22814 TrafficStats            redacted             D  tagSocket(5) with statsTag=0xffffffff, statsUid=-1
2025-01-25 16:25:05.681 22760-22814 AndroidRuntime          redacted             E  FATAL EXCEPTION: DefaultDispatcher-worker-8
                                                                                                    Process: redacted, PID: 22760
2025-01-25 16:25:05.708 22760-22814 Process                 redacted             I  Sending signal. PID: 22760 SIG: 9
```

And here is my code:

```
@file:OptIn(ExperimentalCoroutinesApi::class, ExperimentalUnsignedTypes::class)

package redacted.client.mqtt.client

import co.touchlab.kermit.Logger
import redacted.client.mqtt.client.extension.emptyPayload
import redacted.client.mqtt.client.extension.emptyReceivedPayload
import redacted.client.mqtt.client.extension.toMqttPayload
import redacted.client.mqtt.client.extension.toUnsignedMqttPayload
import redacted.client.mqtt.model.IMqttTopic
import redacted.client.mqtt.model.MqttMessage
import redacted.client.mqtt.model.MqttState
import redacted.client.mqtt.model.Qos
import redacted.client.util.extension.flow.ignoreValue
import redacted.client.util.extension.flow.typedFlow
import redacted.client.util.extension.flow.unitFlow
import io.github.davidepianca98.MQTTClient
import io.github.davidepianca98.mqtt.MQTTVersion
import io.github.davidepianca98.mqtt.Subscription
import io.github.davidepianca98.mqtt.packets.mqtt.MQTTConnack
import io.github.davidepianca98.mqtt.packets.mqtt.MQTTDisconnect
import io.github.davidepianca98.mqtt.packets.mqtt.MQTTPublish
import io.github.davidepianca98.mqtt.packets.mqttv5.ReasonCode
import io.github.davidepianca98.mqtt.packets.mqttv5.SubscriptionOptions
import io.ktor.utils.io.core.*
import kotlinx.coroutines.*
import kotlinx.coroutines.channels.BufferOverflow
import kotlinx.coroutines.flow.*

internal class MqttClientImpl(
    private val isAliveTopic: IMqttTopic,
    private val ioDispatcher: CoroutineDispatcher,
    private val defaultDispatcher: CoroutineDispatcher,
) : MqttClient {

    private val logger = Logger.withTag(LOG_TAG)

    private val _state = MutableStateFlow(MqttState.OFFLINE)
    override val state = _state.asStateFlow()

    private val coroutineScope = CoroutineScope(defaultDispatcher + SupervisorJob())

    private val messagesFlow = MutableSharedFlow<ReceivedMqttMessage>(
        extraBufferCapacity = MESSAGES_BUFFER_CAPACITY,
        onBufferOverflow = BufferOverflow.SUSPEND,
    )

    private var connectionOptions: ConnectionOptions? = null

    private var client: MQTTClient? = null

    private var wasDisconnectInitiated = false

    private val isConnected: Boolean
        get() = client != null && _state.value == MqttState.ONLINE

    override fun connect(clientId: String, host: String, port: Int, userName: String?, password: String?) {
        logger.d { "Connect: clientId=$clientId, host=$host, port=$port, userName=$userName" }

        connectionOptions = ConnectionOptions(
            clientId = clientId,
            host = host,
            port = port,
            userName = userName,
            password = password
        )

        connectInternal()
    }

    private fun connectInternal() {
        logger.d { "connectInternal" }

        wasDisconnectInitiated = false

        val connectionOptions = requireNotNull(this.connectionOptions) {
            "Called connectInternal with null ConnectionOptions"
        }

        _state.value = MqttState.CONNECTING

        val client = MQTTClient(
            mqttVersion = MQTTVersion.MQTT3_1_1,
            address = connectionOptions.host,
            port = connectionOptions.port,
            keepAlive = KEEP_ALIVE_INTERVAL_SECONDS,
            cleanStart = true,
            clientId = connectionOptions.clientId,
            userName = connectionOptions.userName,
            password = connectionOptions.password?.toByteArray()?.toUByteArray(),
            willTopic = isAliveTopic.toString(),
            willPayload = false.toUnsignedMqttPayload(),
            willQos = Qos.EXACTLY_ONCE.toLibraryQos(),
            willRetain = true,
            tls = null, // TODO: Use TLS,
            onConnected = ::onConnected,
            onDisconnected = ::onDisconnected,
            publishReceived = ::onMessageReceived,
        )

        this.client = client

        client.runSuspend(
            dispatcher = defaultDispatcher,
            exceptionHandler = CoroutineExceptionHandler { _, throwable ->
                logger.e(throwable) { "Exception occured in MQTT: ${throwable.message}" }
            }
        )
    }

    override fun disconnect() {
        logger.d { "disconnect" }

        wasDisconnectInitiated = true

        client?.disconnect(ReasonCode.DISCONNECT_WITH_WILL_MESSAGE)
        client = null
    }

    private fun onConnected(connAck: MQTTConnack) {
        logger.d { "onConnected" }

        _state.value = MqttState.ONLINE

        publishAndForget(
            topic = isAliveTopic,
            qos = Qos.EXACTLY_ONCE,
            retain = true,
            payload = true.toMqttPayload(),
            dropIfNotConnected = false,
        )
    }

    private fun onDisconnected(disconnect: MQTTDisconnect?) {
        logger.d { "onDisconnected" }

        _state.value = MqttState.OFFLINE

        if (!wasDisconnectInitiated) {
            logger.d { "Disconnection was not initiated by us, will reconnect after $RECONNECT_DELAY_MS ms" }

            coroutineScope.launch {
                delay(RECONNECT_DELAY_MS)
                connectInternal()
            }
        } else {
            logger.d { "Disconnection was initiated by us, will not reconnect" }
        }
    }

    private fun onMessageReceived(publish: MQTTPublish) {
        coroutineScope.launch(defaultDispatcher) {
            val mqttMessage = MqttMessage(
                id = publish.hashCode(),
                payload = publish.payload?.toByteArray() ?: emptyPayload,
                isRetained = publish.retain,
            )

            val receivedMqttMessage = ReceivedMqttMessage(
                topic = publish.topicName,
                message = mqttMessage,
            )

            messagesFlow.emit(receivedMqttMessage)
        }
    }

    override fun publish(
        topic: String,
        qos: Qos,
        payload: ByteArray,
        retain: Boolean,
        dropIfNotConnected: Boolean,
    ): Flow<Unit> {
        if (dropIfNotConnected && !isConnected) {
            logger.w { "Tried to publish, but not connected, dropping as requested" }
            return unitFlow { }
        }

        return typedFlow { awaitConnection() }
            .flatMapConcat { client ->
                client.publishFlow(
                    topic = topic,
                    qos = qos,
                    payload = payload.toUByteArray(),
                    retain = retain,
                )
            }
            .ignoreValue()
            .flowOn(ioDispatcher)
    }

    private fun MQTTClient.publishFlow(topic: String, qos: Qos, payload: UByteArray, retain: Boolean): Flow<Unit> {
        return unitFlow {
            publish(
                retain = retain,
                qos = qos.toLibraryQos(),
                topic = topic,
                payload = payload,
            )
        }
    }

    override fun publish(
        topic: IMqttTopic,
        qos: Qos,
        payload: ByteArray,
        retain: Boolean,
        dropIfNotConnected: Boolean,
    ): Flow<Unit> {
        return publish(
            topic = topic.toString(),
            qos = qos,
            payload = payload,
            retain = retain,
            dropIfNotConnected = dropIfNotConnected,
        )
    }

    override fun publishAndForget(
        topic: String,
        qos: Qos,
        payload: ByteArray,
        retain: Boolean,
        dropIfNotConnected: Boolean,
    ) {
        coroutineScope.launch {
            publish(
                topic = topic,
                qos = qos,
                payload = payload,
                retain = retain,
                dropIfNotConnected = dropIfNotConnected,
            )
                .catch { t ->
                    logger.e(throwable = t) { "Failed to publish and forget" }
                }
                .collect {}
        }
    }

    override fun publishAndForget(
        topic: IMqttTopic,
        qos: Qos,
        payload: ByteArray,
        retain: Boolean,
        dropIfNotConnected: Boolean,
    ) {
        return publishAndForget(
            topic = topic.toString(),
            qos = qos,
            payload = payload,
            retain = retain,
            dropIfNotConnected = dropIfNotConnected,
        )
    }

    override fun delete(topic: String, qos: Qos): Flow<Unit> {
        return publish(
            topic = topic,
            qos = qos,
            payload = ByteArray(0),
            retain = false
        )
    }

    override fun delete(topic: IMqttTopic, qos: Qos): Flow<Unit> {
        return delete(topic = topic.toString(), qos = qos)
    }

    override fun deleteAndForget(topic: String, qos: Qos) {
        publishAndForget(
            topic = topic,
            qos = qos,
            payload = ByteArray(0),
            retain = false
        )
    }

    override fun deleteAndForget(topic: IMqttTopic, qos: Qos) {
        deleteAndForget(topic = topic.toString(), qos = qos)
    }

    override fun <T> subscribe(
        topicFilter: String,
        qos: Qos,
        messageMapper: (topic: String, message: MqttMessage) -> T?,
    ): Flow<T?> {
        logger.d { "Subscribing to topics with filter=$topicFilter" }
        return typedFlow { awaitConnection() }
            .flatMapConcat { client ->
                val subscription = Subscription(
                    topicFilter = topicFilter,
                    options = SubscriptionOptions(
                        qos = qos.toLibraryQos(),
                    ),
                )
                client.subscribe(listOf(subscription))

                messagesFlow
                    .filter { message ->
                        matchesTopicFilter(message.topic, topicFilter)
                    }
                    .map { message ->
                        val payload = message.message.payload

                        if (payload.isEmpty() || payload.contentEquals(emptyReceivedPayload)) {
                            null
                        } else {
                            messageMapper(message.topic, message.message)
                        }
                    }
                    .flowOn(defaultDispatcher)
            }
    }

    private fun matchesTopicFilter(topic: String, topicFilter: String): Boolean {
        val isWildcard = topicFilter.contains('#') || topicFilter.contains('+')
        if (!isWildcard) {
            return topic == topicFilter
        }

        val topicParts = topic.split('/')
        val filterParts = topicFilter.split('/')

        var topicIndex = 0
        var filterIndex = 0

        while (filterIndex < filterParts.size && topicIndex < topicParts.size) {
            val filterPart = filterParts[filterIndex]
            val topicPart = topicParts[topicIndex]

            when (filterPart) {
                "#" -> return true
                "+", topicPart -> {
                    topicIndex++
                    filterIndex++
                }

                else -> return false // No match
            }
        }

        // Check if both topic and filter are fully consumed
        return (topicIndex == topicParts.size && filterIndex == filterParts.size) ||
                (filterIndex == filterParts.size - 1 && filterParts[filterIndex] == "#")
    }

    override fun <T> subscribe(
        topicFilter: IMqttTopic,
        qos: Qos,
        messageMapper: (topic: String, message: MqttMessage) -> T?,
    ): Flow<T?> {
        return subscribe(
            topicFilter = topicFilter.toString(),
            qos = qos,
            messageMapper = messageMapper
        )
    }

    private suspend fun awaitConnection(): MQTTClient {
        while (!isConnected) {
            delay(AWAIT_CONNECTION_INTERVAL_MS)
        }

        // TODO: Find a better way
        return requireNotNull(client) {
            "Connected client expected not to be null"
        }
    }

    private fun Qos.toLibraryQos(): io.github.davidepianca98.mqtt.packets.Qos {
        return when (this) {
            Qos.AT_MOST_ONCE -> io.github.davidepianca98.mqtt.packets.Qos.AT_MOST_ONCE
            Qos.AT_LEAST_ONCE -> io.github.davidepianca98.mqtt.packets.Qos.AT_LEAST_ONCE
            Qos.EXACTLY_ONCE -> io.github.davidepianca98.mqtt.packets.Qos.EXACTLY_ONCE
        }
    }

    private data class ConnectionOptions(
        val clientId: String,
        val host: String,
        val port: Int,
        val userName: String?,
        val password: String?,
    )

    private data class ReceivedMqttMessage(
        val topic: String,
        val message: MqttMessage,
    )

    private companion object {
        private const val LOG_TAG = "PlatformMqttClient"

        private const val KEEP_ALIVE_INTERVAL_SECONDS = 30
        private const val AWAIT_CONNECTION_INTERVAL_MS = 50L

        private const val RECONNECT_DELAY_MS = 1000L * 1

        private const val MESSAGES_BUFFER_CAPACITY = 512
    }
}
```

**Comment by RankoR** [comment]
@davidepianca98 I've added a demo here: https://github.com/RankoR/kmqtt-android-crash-demo

It crashes every time if you follow the instructions.

**Comment by Tritonfc** [comment]
Hey @RankoR did you eventually get to the bottom of the issue? Having this same problem while trying to set tls settings to the client configuration
